name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.4]
        mongodb-version: [4.4]

    steps:
      - uses: actions/checkout@v2

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Backend testing
        run: npm install && npm install -D && npm test
        env:
          NODE_ENV: test
          PORT: 8080
          DBSTRING: mongodb://localhost:27017/acme-explorer-test
          SWAGGER_SCHEMA: http
          PAYPAL_MODE: sandbox
          PAYPAL_CLIENT_ID: ${{secrets.PAYPAL_CLIENT_ID}}
          PAYPAL_CLIENT_SECRET: ${{secrets.PAYPAL_CLIENT_SECRET}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
